### ISSUE TITLE
Plans for the library

### ISSUE THREAD

**Issue by nordicdev** [LibraryofCode/discordts#7]
### **This is not an real issue**
So there isn't happening anything right now on the repository (mostly since BoD's are busy or something like that).

We could get this rolling and getting commits everyday by doing a road map and giving out roles to people what they have to make, to make this library working and successful.

My plan is that we start planning whole structure of the library and think what we need next after the endpoints (we already implemented almost every). 

Some of the endpoints might be already deprecated since v8 gateway came out lately, and we did pull them from v6 docs - so we have to make sure everything's up to date too.

**Comment by bsian03** [comment]
Going to close this in favour of a new issue (upcoming)
